version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      semver-major-days: 15
      semver-minor-days: 7
      semver-patch-days: 3
    commit-message:
      prefix: "ğŸ¤–(chore)"
      prefix-development: "â¬†ï¸(chore)"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      semver-major-days: 15
      semver-minor-days: 7
      semver-patch-days: 3
    commit-message:
      prefix: "ğŸ¤–(chore)"
      prefix-development: "â¬†ï¸(chore)"

  - package-ecosystem: "docker"
    directories:
      - "/"
      - ".github/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "ğŸ¤–(chore)"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    commit-message:
      prefix: "ğŸ¤–(chore)"
